{% set version = "5.9.0" %}
{% set ver = '.'.join(version.split('.')[:2]) %}

package:
  name: qtwebkit
  version: {{ version }}

source:
  url: http://download.qt.io/community_releases/{{ ver }}/5.9.0-rc2/qtwebkit-opensource-src-5.9.0-rc2.tar.xz
  md5: 2347a1bba296dbf5b535781b69a5a9f9

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - qt 5.9.*

test:
  commands:
    - test -f $PREFIX/lib/libQt5WebKit.dylib  # [osx]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://wiki.qt.io/Qt_WebKit
  license: GPL-3.0
  license_file: LICENSE.GPLv3
  summary: 'WebKit is one of the major engine to render webpages and execute JavaScript code'
  description: |
    Qt WebKit is the port of WebKit on top of Qt. QtWebKit relies on the public APIs of Qt
    and can theoretically be used on any platform supported by Qt
    (theoretically because WebKit also requires a recent/good compiler).

extra:
  recipe-maintainers:
    - ceholden
    - gillins
    - mingwandroid
    - ocefpaf
