travis:
  secure:
    BINSTAR_TOKEN: N6hvevh6j1sPlNE3T6NbIjKZFdZXYf9sciaZmD5xIiLJzf4X4fRZ52SmwvO87FSj6+VC0hoWt6rexF5MVj05cPTDc6XGGVicqDofu4d1cXQX/UBlKHVKDHl8el5voOJTPU7XAzCmZknq8HjMn10USzjFCoX2T5oF9FDDp9garXGBQPIPc4msAeAq+YThCOk/556Uosjp+rgtrn3ABldaYADWfxhNTtEo/rGE9B4r9qkvYOzQpU8Z9L9eNoJR/X0pR7jON70KK0OUR/deoSo95gDvlYNuHxtY/wv0oyK372MicAwOQS1e3BjJA24mZfyMxOxjbj8rxDVFWAYKCeLXdrJ6y1yhD4WMM2y2NmMP/Uf8NWkrB1AuMGAuw2q6kSkJDSvU3cHN1EVQRctMuJOOaeOW7Pt60CZX+CG+oK+861ioQVf0JUJEPlxzpU7GzY0oQ7PT0ayvd7I2EcnnhBBwAYpEvKEsanxBfAW6CmW6GOOFjtGRoCEz/4l4wIssjBaiYJGgHyhedng/pVZTIXSdRDtKagbs+DaNgbeA0dSye9LWpYQ0q3jNWvqG/xSDvmbvR62JM3X4e8vw7b1zz5bWsZO29yy0strdqoQEBLz0IK1EM9K1KbIFoGJ3IrbDrXzikYv6OPDc1AHNlvaOE2imCVH5UU7mueiiIDPt5BJCaQs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
